### ISSUE TITLE
Wiki Design: Discussion

### ISSUE THREAD

**Issue by mykewould** [mykewould/crutches#22]
Initial layout proposal for wiki design. Obviously we want it so that it covers enough information for a beginner to get started. I have no intentions of duplicating efforts around Elixir documentation, but there will be a links section for those who are totally new to the language. Most of the documentation will link to the code where the functions are described in more detail. The FAQ will outline some of the questions and concerns we've talked about in issues and PRs.

Feedback and thoughts always welcome!

Wiki Design (Very rough)
- Welcome
  - Links
- How to Contribute
  - Getting started
  - Styleguide
  - FAQ for contributors
- Documentation
  - Enum
  - Integer
  - Keyword
  - List
  - String

**Comment by mykewould** [comment]
style guide https://github.com/niftyn8/elixir_style_guide

**Comment by duijf** [comment]
Hi Michael,

The wiki, IMHO should be reserved for things like project philosophy and the FAQ. Docs and contributing information have better places.
- `CONTRIBUTING.md` &mdash; a markdown file that [GitHub will link to](https://github.com/blog/1184-contributing-guidelines) when someone wants to open an issue or PR. This could contain everything that you put under the "How to Contribute" category.
- http://hexdocs.pm/ &mdash; the recommended place to store documentation of Elixir modules. This is auto generated from the `@doc` and `@moduledoc` model attributes and offers lower maintenance documentation than keeping wiki pages in sync with the source. Another added benefit is that the documentation is versioned (which is a huge challenge to keep in sync manually).

And maybe the following is helpful to include in the contributors guide in addition to what you came up with:
- The best way to make sure your PR can be merged in cleanly while keeping the history nice (rebase with master and force push instead of merging&mdash;or any other flow, I just like this one).
- Commit message template (if we want to standardise this).
- How to run the tests and install the dependencies.
- Template for a bug report.
- What gets merged, what doesn't and why (needs to be decided first).

**Comment by mykewould** [comment]
Love it @duijf. I agree.

**Comment by mykewould** [comment]
Added hexdocs.

**Comment by druzn3k** [comment]
Added `CONTRIBUTING.md`

**Comment by mykewould** [comment]
I'll make some alterations to the wiki, but I'm closing this for until more specific wiki questions arise.
