### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by druzn3k** [mykewould/crutches#40]
I think we should start thinking about internationalization. The porting of the `NumberHelpers` module has given this issue a boost on priority. Otherwise, the number helpers are mostly useless outside of USA. I think that [linguist](https://github.com/chrismccord/linguist) could be really easy to integrate. But, on the other hand, I think that the less dependencies we have, the better. Thoughts?

**Comment by jesuspc** [comment]
I would take the same approach as ActiveSupport did and include the most popular internationalization library as a dependency. Otherwise a lot of noise is going to be added into the repo in order to support a small subset of functionalities. Furthermore, it is not likely to be using the **locale** parameter in a project that does not already require some sort of internationalization library (which is going to default to Linguist) so if we don't provide it directly from Crutches (something like Crutches.I18n) users would need an internationalization config for the regular library and another for Crutches.

**Comment by duijf** [comment]
Elixir has a new approach to internationalisation, `gettext` (https://github.com/elixir-lang/gettext). I think this is something that is covered elsewhere. Closing the internationalisation issues.
