### ISSUE TITLE
Do you have a list of issues that are coming?

### ISSUE THREAD

**Issue by jdl** [mykewould/crutches#72]
Hey there. 
I saw your post on reddit and this looks like a fun project to help with. I'm an Elixir newbie, but the easier issues seem like a great place to start. Seems like they're all being worked on though. Do you have more coming soon, or a suggestion for a missing feature?

**Comment by druzn3k** [comment]
There is no list, unfortunately. But there is sure a lot of work to do, for example, [overlaps?](http://guides.rubyonrails.org/active_support_core_extensions.html#overlaps-questionmark) is a good candidate because it's simple. And we are open to proposals, so if you want to implement a method, even if is not part of ActiveSupport, you could open an issue and we could discuss if the functionality fits the library purpose.

**Comment by jdl** [comment]
overlaps? sounds conceptually simple enough. I'll give it a shot. Would you think that a range.ex file is appropriate in /lib for this?

**Comment by CyrusNuevoDia** [comment]
@jdl it sounds perfect :shipit: :smile:

**Comment by druzn3k** [comment]
closed
