### ISSUE TITLE
RFC: UnionRange / ComplexRange

### ISSUE THREAD

**Issue by druzn3k** [mykewould/crutches#75]
Should we build a data structure based on `Range` that consist in the uninion of **n** `Range`s or is out of scope? Should this live in a different project? Could be another library for kickstarting people in the world of Elixir!

**Comment by CyrusNuevoDia** [comment]
On one hand there's adhering to set theory, on the other hand I can't find any other programming language that does this. I'd be willing to write it just for the sake of saying we have it, but just because we can, doesn't mean we should.

It would inevitably have to be a struct containing a list of ranges, because a 'complex' range wouldn't be limited to just 2 ranges.

``` elixir
%Crutches.Range{
  sets: [1..4, 12..19, 101..78]
}
```

Also, re: naming, UnionRange is too specific and ComplexRange implies using the complex numbers. @duijf, any naming suggestions?

**Comment by druzn3k** [comment]
MultipleRange? :)
Il 21/ago/2015 14:10, "Kash Nouroozi" notifications@github.com ha scritto:

**Comment by duijf** [comment]
The more I think about the general use cases of this, the more I think it is out of scope of this project, since the number of use-cases is quite small.

(I also doubt the usefulness in a library of it's own. Needing stuff like this, I think, is likely because of business requirements, which come with a lot of domain specific rules that you cannot include in a library. If there would only be a few functions in the library, I'd probably write those myself.)

I don't mean to shoot anything down though, @druzn3k. If you think that there is a concrete need for it, then by all means go for it! I just don't see it yet.

**Comment by druzn3k** [comment]
No worries @duijf. :+1: I was just doing a follow-up to the discussion in the other issue. :smile:
